<%
if (Request.QueryString("frame") != "yes")
{
%>
<div style="margin-left:-10px; margin-right: -10px; font-family: tahoma,arial;margin-left:-10px; background-color: #F4F4F4; border-bottom: 1px solid threedshadow">
<table border="0" width="100%" cellspacing="0" cellpadding="0" ><tr><td>
<a href="http://www.expressionblogs.net" target="_blank"><img border="0" src="../images/expressionBanner.jpg" width="262" height="55" alt="eXpression Blogging and Website Engine"></td>
<td valign="middle" align="right" style="font-family:arial,helvetica;font-size:12px">By: <a href="https://github.com/codepoet80" target="_blank">codepoet80</a>&nbsp;</td>
</tr></table>
</div>
<%
}
%>